global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["3.109.122.18:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
    - targets: ["3.109.122.18:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
    - targets: ["cadvisor:8080"]
